name: Build on push

on:
  push:
    branches:
      - 'extension-release-*'

jobs:
  build-all:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false,
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Create a chrome zip
        run: zip -r chrome.zip *
        working-directory: ./dist/chrome
      - name: Create a firefox zip
        run: zip -r firefox.zip *
        working-directory: ./dist/firefox
