name: Release on create

on:
  push:
    branches:
      - extension-release-*

jobs:
  release-on-create:
    if: github.event.created
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false,
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - run: sudo apt-get update
      - name: configure github auth for npm
        run: git config --global url."https://${{ secrets.GH_DEPENDENCIES_TOKEN }}:x-oauth-basic@github.com/".insteadOf https://x-oauth-basic@github.com/
      - name: Install NPM Dependencies
        run: npm ci --silent | cat

#      - name: Create dev chrome zip
#        run: zip -r chrome-dev.zip *
#        working-directory: ./dist/chrome-dev
#
#      - name: Create production chrome zip
#        run: zip -r chrome.zip *
#        working-directory: ./dist/chrome-prod
#
#      - name: Create production firefox zip
#        run: zip -r firefox.zip *
#        working-directory: ./dist/firefox-prod
#
#      - name: Create firefox source zip
#        run: zip -r firefox-source.zip *
#        working-directory: ./dist/firefox-source
#
#      - name: Create a production edge zip
#        run: zip -r edge.zip *
#        working-directory: ./dist/edge-prod
#
#      - name: Build dev chrome extension
#        run: npm run chrome-dev -- --env version=1.2.3
#      - name: Build production chrome extension
#        run: npm run chrome-prod -- --env version=1.2.3
#      - name: Build production firefox extension
#        run: npm run firefox-release
#      - name: Build production edge extension
#        run: npm run edge-prod

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: major
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: dist/chrome/chrome.zip, dist/firefox/firefox.zip
